language:
  python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install flake8
  - pip install coverage
  - pip install -r requirements.txt

script:
  - flake8 opwen_email_client
  - nosetests $(find tests -name '*.py') --with-coverage --cover-branches --cover-erase --cover-package=opwen_email_client
